### ISSUE TITLE
add Platform Cooperativism Consortium, DisCo project (Distributed Cooperative Organizations)

### ISSUE THREAD

**Issue by CirKu17** [Tech-Workers-Coalition-Italia/awesome-coop-it#4]
Platform coop: 

- https://platform.coop/
- https://resources.platform.coop/

DisCo:

- https://disco.coop/disco-project/
- https://disco.coop/governance-model/

**Comment by tinoilcotechino** [comment]
fixed in a81bf5bf14b68fe71c190733efb6b7bcc5d43dfc
